---
title: "Data loading"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## R Markdown


```{r}
library(readr)
library(dplyr)
library(reshape2)
library(ggplot2)



#assign vectors 
valid_weeks<- c('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52')
later_weeks<- c('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20')
first_weeks<- c('43', '44', '45', '46', '47', '48', '49', '50', '51', '52')
seasons<- c('2010/2011', '2011/2012', '2012/2013', '2013/2014', '2014/2015', '2015/2016', '2016/2017')
regions<- c('HHS Region 1', 'HHS Region 2','HHS Region 3','HHS Region 4','HHS Region 5','HHS Region 6','HHS Region 7','HHS Region 8','HHS Region 9','HHS Region 10')
targets<- c('1 wk ahead', '2 wk ahead','3 wk ahead','4 wk ahead','Season peak percentage')
weeks_as_ints<- c(1:20, 43:52)


#function reads in 210 cvs from 1 ensemble model, adds week and year columns and binds them 
      #path: string sim. to 'model-forecasts/cv-ensemble-models/constant-weights/EW%s-%s-constant-weights.csv'
      #start_wk: where in string model week is mentioned
      #start_yr: where in string model year is mentioned
import<- function(path, start_wk, start_yr){     
  data<- rbind()
  for(week in valid_weeks){
    for (year in 2010:2017){
      if (!(week %in% later_weeks & year =='2010') & !(week %in% first_weeks & year =='2017')){
        str<- sprintf(path, week, year)
        new<- read_csv(str)
        new$week<- rep(as.numeric(substr(str,start_wk,start_wk+1)), nrow(new)) #adds column: week 
        new$year<- rep(as.numeric(substr(str,start_yr, start_yr+3)),nrow(new)) #adds column: year 
        data<- rbind(data, new)}
    }
  }
  return(data)
}

#import() all ensemble models 

#**impt: in order for other people to run from dif. directories, will need general code for start_wk and start_yr
constant_weights<- import('~/Desktop/PIT_git/model-forecasts/cv-ensemble-models/constant-weights/EW%s-%s-constant-weights.csv', 73, 76)
equal_weights<- import('~/Desktop/PIT_git/model-forecasts/cv-ensemble-models/equal-weights/EW%s-%s-equal-weights.csv', 70, 73)
target_region_weights<- import('~/Desktop/PIT_git/model-forecasts/cv-ensemble-models/target-and-region-based-weights/EW%s-%s-target-and-region-based-weights.csv', 88, 91)
target_weights<- import('~/Desktop/PIT_git/model-forecasts/cv-ensemble-models/target-based-weights/EW%s-%s-target-based-weights.csv', 77, 80)
target_type_weights<-import('~/Desktop/PIT_git/model-forecasts/cv-ensemble-models/target-type-based-weights/EW%s-%s-target-type-based-weights.csv', 82, 85)

#function for tidy data:
make_tidy<- function(ensemble){
  tidy<- ensemble %>% filter(location !=  'US National', target != 'week') %>% mutate(Season = ifelse(week > 30, paste(year, year+1, sep = "/"), paste(year-1, year, sep= "/")))
  return(tidy)
}

constant_weights%>% 

#tidy all ensembles
constant_weights_tidy<- make_tidy(constant_weights)
equal_weights_tidy<- make_tidy(equal_weights)
target_region_weights_tidy<- make_tidy(target_region_weights)
target_weights_tidy<- make_tidy(target_weights)
target_type_weights_tidy<- make_tidy(target_type_weights)

```

True data that will be used for all PIT values/histograms 
```{r}
true<- read_csv('~/Desktop/PIT_git/scores/target-multivals.csv')

names(true) <- gsub(" ", "_", names(true))
true_tidy<- true %>% 
  filter(Location != 'US National', Target %in% c('1 wk ahead', '2 wk ahead', '3 wk ahead', '4 wk ahead', 'Season peak percentage'))
```

Functions for PIT
```{r}
#gets true observation from dataframe true_tidy 
get_true<- function(CW, Seas, Loca, Tar){   
  obs <- true_tidy %>% filter(Calendar_Week == CW,Season== Seas, Location == Loca, Target==Tar) %>% select(Valid_Bin_start_incl)
  return(as.numeric(obs))
}
get_true(1,'2010/2011', 'HHS Region 1', '1 wk ahead')

#emipical cdf function returns pit value 
    #q: observed value of wili, q is for 'quantile' bc asking for quantile of observed value
    #percents: vector of percentages for possibile wili values 
empirical_cdf <- function(q, percents){   
  bin_index <- 0
  for (wili in seq(0.1,13.1,.1)){  #wili= weighted influenza-like illness (%), seq rep. bins which rep. wili
    if (q < wili){
      break
    }
    bin_index <- bin_index + 1
  }
  return (cumsum(percents)[bin_index])
}


#generates ~10,500 pit values from ensemble model: uses functions empirical_cdf() and get_true()
#10 minutes to run 
generate_all_pit_values<- function(ensemble_data){
  pit_values<- c()
    for (s in seasons){
      for (w in weeks_as_ints){
        for (r in regions){
          for(t in targets){
            df<- ensemble_data %>% filter(location== r, target== t, Season== s, week==w) 
            percents <- df$value[1:length(df$value)-1]
            q<-get_true(w,s,r,t)
            pit_values<- c(pit_values,empirical_cdf(q, percents))
          }
        }
      }
    }
  return(pit_values)
}

#apply generate_all_pit_values() for all ensemble models
#'all' means ALL targets, regions, seasons, and weeks
all_pit_constant<- generate_all_pit_values(constant_weights_tidy)
hist(all_pit_constant, freq=F)

all_pit_equal<- generate_all_pit_values(equal_weights_tidy)
hist(all_pit_equal, freq=F)

all_pit_target_region<- generate_all_pit_values(target_region_weights_tidy)
hist(all_pit_target_region, freq= F)  #look skewed

all_pit_target_type<-generate_all_pit_values(target_weights_tidy)

all_pit_target<- generate_all_pit_values(target_type_weights_tidy)


#generates histogram plot
pit_histogram<- function(pit_values){
  return(hist(pit_values, freq=F))
}

#add acf graph
```








breaking models up by region and target 
```{r}

#start w cw

#want to generate sep pit vectors for each target (then region, then region and target) 
#function that depends on target and model 

target_pit_values<- function(model, tar){
  pit_values<- c()
    for (s in seasons){
      for (w in weeks_as_ints){
        for (r in regions){
          df<- model %>% filter(location== r, target== tar, Season== s, week==w) 
            percents <- df$value[1:length(df$value)-1]
            q<-get_true(w,s,r,tar)
            pit_values<- c(pit_values,empirical_cdf(q, percents))
        }
      }
    }
  return(pit_vales)
}
#for cw and all targets     
wk1_cw <- target_pit_values(constant_weights_tidy, '1 wk ahead')  #haven't run yet
wk2_cw <- target_pit_values(constant_weights_tidy, '2 wk ahead')
wk3_cw <- target_pit_values(constant_weights_tidy, '3 wk ahead')
wk4_cw <-  target_pit_values(constant_weights_tidy, '4 wk ahead')
peak_wk_cw <- target_pit_values(constant_weights_tidy, 'Season peak percentage')

#function for pit values of regions 
regions_pit_values<- function(model, reg){
  pit_values<- c()
    for (s in seasons){
      for (w in weeks_as_ints){
        for (t in targets){
          df<- model %>% filter(location== reg, target== t, Season== s, week==w) 
            percents <- df$value[1:length(df$value)-1]
            q<-get_true(w,s,reg,t)
            pit_values<- c(pit_values,empirical_cdf(q, percents))
        }
      }
    }
  return(pit_vales)
}

#function for pit values of regions and targets 
target_and_region_pit_values<- function(model, tar, reg){
  pit_values<- c()
    for (s in seasons){
      for (w in weeks_as_ints){
          #could make next 4 lines a function and not include for loops in generate_pit_values()
          df<- model %>% filter(location== reg, target== tar, Season== s, week==w) 
          percents <- df$value[1:length(df$value)-1]
          q<-get_true(w,s,reg,tar)
          pit_values<- c(pit_values,empirical_cdf(q, percents))
      }
    }
  return(pit_vales)
}

#50 possible combinations of target and region.. how to make function? vector of vector? 

wk1_HHS1 <- target_and_region_pit_values(constant_weights_tidy,'1 wk ahead', 'HHS Region 1')
#hist()

```


