---
title: "EW01-2011 w KDE cdf method"
author: "Rebecca Silva"
date: "July 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(readr)
library(dplyr)
data<- read_csv("https://raw.githubusercontent.com/rsilva19/cdc-flusight-ensemble/master/model-forecasts/cv-ensemble-models/constant-weights/EW01-2011-constant-weights.csv")
true<- read_csv("https://raw.githubusercontent.com/FluSightNetwork/cdc-flusight-ensemble/master/scores/target-multivals.csv")

str(true)



wk1r1<- filter(data, location== 'HHS Region 1', target=='Season peak percentage')
values_test <- wk1r1$value[1:130]
values<- wk1r1$value[1:length(wk1r1$value)-1]
#why does this work but: wk1r1$value[1:length(wk1r1$value)-2] doesnt 
#par(mfrow=c(1,2))

plot(seq(0.05,13.1,.1), values)  #pdf
plot(seq(0.05,13.0,.1), values_test) 
plot(seq(0.05,13.1,.1),cumsum(values))   
plot(seq(0.05,13.0,.1),cumsum(values_test))           #cdf

     
empirical_cdf_test <- function(q, values){
  bin_index <- 0
  for (wili in seq(0.1,13.0,.1)){
    if (q < wili){
      break
    }
    bin_index <- bin_index + 1
  }
  return (cumsum(values)[bin_index])
}

#finding q from true data 
str(true)
q<- true %>% filter('Year'== 2011, Calendar Week == 1, Target =='1 wk ahead', Model Week == 53, Location=='Season peak percentage')
as.numeric(q)

empirical_cdf_test(2, values_test) 
empirical_cdf(2, wk1r1$value) 

```


```{r}

sample<- sample(x =seq(0,12.9,bin_iter_size), n, replace = T, prob = values_test) 


sample_other<- sample(x =seq(0,13.0,bin_iter_size), n, replace = T, prob = values) 

#show slight difference in sample (weighted more correctly with )
hist(sample, freq=F)
hist(sample_other, freq=F)


pit_values<- c(pit_values,kernel_density_cdf(q, sample))

#sampleDist_wili_test <-  function(values,n ) { 
dist_test<- sample(x =seq(0,13,bin_iter_size), n, replace = T, prob = values) 
    #return(dist)
#}

```