---
title: "MSE vs PIT"
author: "Rebecca Silva"
date: "June 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}

## GOOD MSE BAD PIT / dat is not from a dist 

ndist <- 1000000
mu <- 1:ndist
s <- rchisq(ndist, 3)
# expected value is mu
dat <- mu   #rnorm(ndist, mean=mu, sd=s)
qtiles <- pnorm(dat, mean=mu, sd=s)

hist(qtiles,xlim=c(0,1))

print (mean((mu-dat)^2))

## BAD MSE GOOD PIT  /nicks original code 

ndist <- 1000000
mu <- 1:ndist
s <- rchisq(ndist, 3)
# expected value is mu
dat <- rnorm(ndist, mean=mu, sd=s)
qtiles <- pnorm(dat, mean=mu, sd=s)

hist(qtiles,xlim=c(0,1))

print (mean((mu-dat)^2))


### GOOD MSE GOOD PIT (SAME DIST)
mu <- rep(1,ndist)
s <- rep(1,ndist)
dat <- rnorm(ndist, mean=mu, sd=s)
qtiles <- pnorm(dat, mean=mu, sd=s)

hist(qtiles,xlim=c(0,1))

print (mean((mu-dat)^2))



#DOESN'T WORK
ndist <- 10000
mu <- 1:ndist
s <- rchisq(ndist, .1)
# expected value is mu
dat <- rnorm(ndist, mean=mu, sd=s)
qtiles <- pnorm(dat, mean=mu, sd=s)
#plot(s)
hist(qtiles,xlim=c(0,1))

print (mean((mu-dat)^2))


# WORKS
mu <- rep(1,ndist)
s <- rep(.1,ndist)
dat <- rnorm(ndist, mean=mu, sd=s)
qtiles <- pnorm(dat, mean=mu, sd=s)

hist(qtiles)



```
